export const PORT = 'PORT';
export const SECRET_KEY = 'SECRET_KEY';
export const GENERATOR_SERVICE_CLIENT_SECRET =
  'GENERATOR_SERVICE_CLIENT_SECRET';
export const GENERATOR_SERVICE_CLIENT_ID = 'GENERATOR_SERVICE_CLIENT_ID';
export const GOOGLE_APPLICATION_CREDENTIALS = 'GOOGLE_APPLICATION_CREDENTIALS';
export const FIREBASE_EMAIL = 'FIREBASE_EMAIL';
export const FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY';
export const FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID';

// ERROR CODES
export const ERROR_USER_SUBSCRIPTION_ALREADY_ACTIVE =
  'USER_SERVICE_ERROR_1: User already has active subscription';
export const ERROR_CUSTOMER_DELETED =
  'USER_SERVICE_ERROR_2: Stripe customer is deleted';

export const ERROR_CUSTOMER_NOT_FOUND =
  'USER_SERVICE_ERROR_3: Stripe customer not found';

export const ERROR_CANNOT_CHANGE_WEBSITE_IDENTIFIER =
  'USER_SERVICE_ERROR_4: Cannot change website identifier after already set';
